name: Update Contributors

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
        with:
          submodules: recursive
      - name: Get contributors information
        uses: "arsulegai/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: arsulegai/hyperledger-updates
          CONTRIBUTORS_SECTION_PATTERN: "# Backend Contributors"
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./index.md
      - name: Create Pull Request with new backend contributors
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          title: Update Backend Contributors
          labels: automerge
          signoff: true
          delete-branch: false
          commit-message: Update Backend Contributors
